#spring:
#  mvc:
#    static-path-pattern: /static/**

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123!
  jdbc:
    template:
      query-timeout: 3

mybatis:
  configuration:
    map-underscore-to-camel-case: true